### ISSUE TITLE
Cookbook is incompatible with Chef client 13

### ISSUE THREAD

**Issue by kkeane** [chef-cookbooks/logwatch#9]
### Cookbook version
2.1.0

### Chef-client version
13.0.113

### Platform Details
CentOS 6 (probably all platforms)

### Scenario:
Any chef run with this cookbook in the run list fails because logwatch depends on an ancient version of the perl cookbook.

### Steps to Reproduce:
- create a blank cookbook.
- add depends 'logwatch', '> 2.0.0' to the metadata.rb file
- run berks install
- note that it pulls in perl 1.2.4 instead of the current perl 5.1.0
- run berks upload
- add this cookbook to any run list.
- do a chef run and notice it error out in the perl cookbook.

Note: there is a variation of this scenario. If you are using the perl 5.1.0 cookbook elsewhere, and you don't pin the logwatch version, then berkshelf will instead pick an older version of logwatch (1.0.2 in my case) that does not pin the perl version, but has other problems.

### Expected Result:
berk install should use perl 5.1.0, and a chef run using logwatch should complete without error.

### Actual Result:
berks install will use perl 1.2.4, and a chef run using logwatch errors out due to an incompatibility with chef 13.

**Comment by tas50** [comment]
@kkeane This cookbook should be fully compatible with Chef 13. We're requiring perl >= 1.2, which will allow you to use all the way up to the current release. If you're running `berks install` you won't actually pull in the latest and great cookbooks though. You'll want to run `berks update` to pull in the latest cookbook versions, which should give you the perl you need. 

If you're still not seeing the latest perl, then another cookbook in your runlist is constraining the version of perl to one that isn't compatible with Chef 13.  A really handy way to figure this out is to run `berks viz`, which gives you a visual map of the dependencies. I've attached the berks viz for just the logwatch cookbook, which is pretty straight forward and allow for anything equal to or newer than 1.2

![graph](https://cloud.githubusercontent.com/assets/1015200/24882880/8c317420-1df7-11e7-8a3d-470213e5cb60.png)

**Comment by kkeane** [comment]
Version 2.1.0 had perl as ~> 1.2.0 rather than => 1.2.0. Since somebody uploaded version 2.1.1 to the supermarket in the meantime, this problem is now resolved. Thanks for being so responsive!
